In [13]:
import sys
from pathlib import Path

import pandas as pd
import requests

sys.path.insert(0, str(Path.cwd().parent / 'src'))
from aimdl_examples import (
    get_girder_client,
    fetch_and_parse,
    coerce_types,
    paginate_datafiles,
)

In [14]:
with requests.Session() as session:
    gc = get_girder_client(session=session)
    rows = paginate_datafiles(
        gc,
        "pdv_alpss_result",
        worker_fn=lambda item: fetch_and_parse(gc, item)
    )
    print(rows[0])
    df = pd.DataFrame(rows)
    df = coerce_types(df)

{'Date': 'Jun 10 2026 01:55 PM', 'File Name': 'C1--20250807--00004.csv', 'Run Time': '0 days 00:00:00.796325', 'Error Message': 'velocity: Velocity 3.117297465239656 did not exceed minimum velocity of (25); spall: skipping velocity_ok=False bool(props)=False; spall_uncertainty: skipping spall_ok=False, velocity_ok=False, bool(props)=False; hel: skipping velocity_ok=False bool(props)=False; shock: skipping velocity_ok=False bool(props)=False', 'Velocity OK': False, 'Velocity at Max Compression': 3.117297465239656, 'Time at Max Compression': 1.996117188e-06, 'Velocity at Max Compression Freq Uncertainty': 1323285.8530191863, 'Velocity at Max Compression Vel Uncertainty': 1.0255465360898697, 'Carrier Frequency': 1796000000.0, 'Spect Time Res': 6.015624999999998e-10, 'Spect Freq Res': 25000000.0, 'Spect Velocity Res': 19.375, 'Signal Start Time': 1.997523438e-06, 'Smoothing Characteristic Time': 1.8311718749999998e-09, 'Spall Enabled': True, 'Spall OK': False, 'Uncertainty OK': False, 'HEL Enabled': True, 'HEL OK': False, 'HEL Consecutive Points': 0, 'igsn': 'JHAMAA00001-S5R4C3', 'itemId': '6a296cc90b116ccbfdcc1f72'}

In [15]:
df.head()

,Date,File Name,Run Time,Error Message,Velocity OK,Velocity at Max Compression,Time at Max Compression,Velocity at Max Compression Freq Uncertainty,Velocity at Max Compression Vel Uncertainty,Carrier Frequency,...,Strain Rate,Spall Strength Uncertainty,Strain Rate Uncertainty,HEL Strength (GPa),HEL Uncertainty (GPa),HEL Free Surface Velocity (m/s),HEL Time Detection (ns),HEL Segment Duration (ns),HEL Strain Rate,Peak Shock Stress
0,Jun 10 2026 01:55 PM,C1--20250807--00004.csv,0 days 00:00:00.796325,velocity: Velocity 3.117297465239656 did not e...,False,3.117297,0.000002,1.323286e+06,1.025547,1.796000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jun 10 2026 01:55 PM,C1--20250807--00009.csv,0 days 00:00:00.778187,velocity: Velocity 1.013024448780469 did not e...,False,1.013024,0.000002,1.813703e+06,1.405619,1.860058e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jun 10 2026 01:55 PM,C1--20250807--00005.csv,0 days 00:00:00.797174,velocity: Velocity 2.317337597437216 did not e...,False,2.317338,0.000002,1.345923e+06,1.043090,1.824000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jun 10 2026 01:54 PM,C1--20250807--00002.csv,0 days 00:00:00.789077,velocity: Velocity 2.1699861103704454 did not ...,False,2.169986,0.000002,8.506122e+05,0.659224,1.852000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jun 10 2026 01:55 PM,C1--20250807--00008.csv,0 days 00:00:00.791731,velocity: Velocity 2.379953845231893 did not e...,False,2.379954,0.000002,1.343252e+06,1.041020,1.840000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df[df['Velocity OK'] == True].head()

,Date,File Name,Run Time,Error Message,Velocity OK,Velocity at Max Compression,Time at Max Compression,Velocity at Max Compression Freq Uncertainty,Velocity at Max Compression Vel Uncertainty,Carrier Frequency,...,Strain Rate,Spall Strength Uncertainty,Strain Rate Uncertainty,HEL Strength (GPa),HEL Uncertainty (GPa),HEL Free Surface Velocity (m/s),HEL Time Detection (ns),HEL Segment Duration (ns),HEL Strain Rate,Peak Shock Stress
25,Jun 10 2026 01:53 PM,C1--20250807--00028.csv,0 days 00:00:00.890308,spall: skipping velocity_ok=True bool(props)=F...,True,342.820936,0.000002,7.367634e+05,0.570992,1.840058e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Jun 10 2026 01:53 PM,C1--20250807--00026.csv,0 days 00:00:00.947536,spall: skipping velocity_ok=True bool(props)=F...,True,353.049451,0.000002,6.699594e+05,0.519219,1.776056e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Jun 10 2026 01:54 PM,C1--20250807--00035.csv,0 days 00:00:00.886475,spall: skipping velocity_ok=True bool(props)=F...,True,350.623525,0.000002,1.321728e+06,1.024339,1.836000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Jun 10 2026 01:54 PM,C1--20250807--00034.csv,0 days 00:00:00.884813,spall: skipping velocity_ok=True bool(props)=F...,True,332.378504,0.000002,1.487001e+06,1.152426,1.812057e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Jun 10 2026 01:55 PM,C1--20250807--00044.csv,0 days 00:00:00.757938,spall: skipping velocity_ok=True bool(props)=F...,True,60.828302,0.000002,2.630700e+06,2.038793,1.852000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN